### PR TITLE
Community/Stories Refactor and Paginate Component

### PR DESCRIPTION
**Pull request by okbel**
## What does this PR do?
- Community Refactor and Stories Refactor
- New Paginate Component 
- Support for Pagination on Search (Community/People)
- Support for Pagination on Search (Stories)
- Fully implement sorting, filter on Stories
- WIP e2e

### CODE REVIEW

**Review by kgardnr — APPROVED** [review]
Awesome! 💯

**Review by alinhle — COMMENTED** [review]
image

Paginate does not follow the results of a search (yet)

**Review by alinhle — CHANGES_REQUESTED** [review]
image

Stories do not paginate (yet)

**Review by alinhle — APPROVED** [review]
Again approving all but my own changes ;-)

**Pull request merged**
