### PR TITLE
Fix deselect bug of action menu in ff

### PR DESCRIPTION
**Pull request by alinhle**
## What does this PR do?
- https://www.pivotaltracker.com/story/show/154183787

## How do I test this PR?
- In firefox, click on `actions` menu for banning / suspending a user
- Click outside and the menu should "deselect"

### CODE REVIEW

**Comment by wyattjoh** [comment]
I'm still seeing the box stay gray after I select an option from the dropdown.

Reproduce:

1. Suspend a user
2. Unsuspend a user
3. Notice that the box is remaining, selected and gray

**Comment by kgardnr** [comment]
@cvle @wyattjoh I see the same as well

**Comment by alinhle** [comment]
on it

**Comment by alinhle** [comment]
@wyattjoh @kgardnr done!

**Review by wyattjoh — APPROVED** [review]

**Pull request merged**
