### PR TITLE
added native comments pdf

### PR DESCRIPTION
**Pull request by immber**
## What does this PR do?
Adds new page to documentation on native mobile app dev

## How do I test this PR?

- Test the netlify preview

### CODE REVIEW

**Comment by immber** [comment]
@kgardnr This should be ready to merge if you approve the changes and language!

**Comment by kgardnr** [comment]
Can you change the text to:

When it comes mobile devices, the Talk client embed is already responsive and mobile friendly. We do not currently have plans to provide mobile SDKs, however, you can do this yourself. 

One organization that has taken on the challenge of creating their own iOS native Talk client is [IGN](https://ign.com). They were kind enough to share how they implemented Talk natively on their apps, which can be found [here](/talk/images/IGNNativeComments.pdf).

If you implement Talk on your mobile apps and would like to contribute your process for others, you can add those here in our docs via a PR or post an issue on Github and we can help you.

**Review by kgardnr — CHANGES_REQUESTED** [review]
Added some copy changes! Thanks @immber!

**Review by immber — COMMENTED** [review]
@kgardnr Copy changed, and PDF file moved to our WP static file host

**Review by kgardnr — APPROVED** [review]

**Pull request merged**
