### PR TITLE
[CORL-591] add reactions to my comments history

### PR DESCRIPTION
**Pull request by tessalt**
## What does this PR do?
Adds reaction count to comment history view under profile tab

image

## How do I test this PR?
- have a comment that has been reacted to
- view comment in comment history

### CODE REVIEW

**Comment by kgardnr** [comment]
@tessalt small thing, could you make it "2 Reactions", if possible?

**Comment by tessalt** [comment]
@kgardnr i think i actually got this backwards from the main stream, where its `Reacted 2`

**Comment by tessalt** [comment]
or wait now im confused neither might be true will look.

**Comment by kgardnr** [comment]
@tessalt ah okay, good point! LGTM 👍

**Review by wyattjoh — APPROVED** [review]

**Pull request merged**
