### PR TITLE
add a little keyboard shortcut hint widget

### PR DESCRIPTION
**Pull request by riley**
## What does this PR do?

in the moderation queue, there was no way to know that there were keyboard shortcuts. Now there's a little hint thing that can be dismissed letting you know that there's a wealth of shortcuts at your fingertips!

## How do I test this PR?

- view the moderation queue
- there should be a little shortcut thing there
- dismiss it
- reload the page; it should no longer be there

### CODE REVIEW

**Comment by gabelula** [comment]
There is nothing that tells me how to have that box up again. Is that ok?

**Comment by riley** [comment]
@IAmSamHankins should we add something that will allow you to bring up the hint box again?

**Comment by theysamtheirs** [comment]
@riley @gabelula i would say it isn't needed. the pattern typically involves someone clicking "dismiss" because they longer want to see it/hints. we are also keeping the keyboard shortcuts menu in the "cog" in the upper right for user reference.

**Review by gabelula — APPROVED** [review]
It looks good to me.

**Review by alinhle — CHANGES_REQUESTED** [review]
Can we put the `ui state` into `redux`? I wouldn't want to manage another layer of `state` in the `localStorage`. 

The best was for me is to sync the `localStorage` inside `redux`, e.g:

Load `initialState` from `localStorage` and during an `action` update both the `redux` and the `localStorage`.

**Comment by alinhle** [comment]
That way we keep our `redux` store authoritative for all ui state and we are flexible with `actions` and other `redux` related advantages.

**Review by alinhle — APPROVED** [review]
Awesome @riley! This can be merged, after someone tested it.

**Comment by okbel** [comment]
💯

**Comment by okbel** [comment]
Let's merge when the CI ends testing.

**Pull request merged**
