### PR TITLE
Show/hide a comment's edit history from Moderation and User Detail.

### PR DESCRIPTION
**Pull request by gerardogalvez**
## What does this PR do?
Add a "toggle" in the comments cards in Moderation and User Detail to be able to see the comment's edit history.

(#1951)

## How do I test this PR?
1. Find an edited comment either in a moderation queue or user details.
2. Click on Show edit history
3. Click on Hide edit history

Moderation queue:

User details:

### CODE REVIEW

**Comment by kgardnr** [comment]
Wow, thank you so much @gerardogalvez! We will review this and get back to you!

**Comment by theysamtheirs** [comment]
hey @gerardogalvez this looks really great! one small design change, if we could have the date/timestamp be on its own line and then have the comment content on the next line, that would really help out with the readability of longer comments! thanks!

**Comment by gerardogalvez** [comment]
Sure! I'll have it done on these coming days!

**Review by kgardnr — APPROVED** [review]

**Comment by alinhle** [comment]
Thank you so much @gerardogalvez!

**Pull request merged**
