### PR TITLE
Some useful style classes

### PR DESCRIPTION
**Pull request by cristiandean**

### CODE REVIEW

**Comment by kgardnr** [comment]
Hey @cristiandean, thank you for this! I'll get @cvle to look at this next week for you!

**Comment by cristiandean** [comment]
Thank you @kgardnr. The tests are passing now

**Comment by alinhle** [comment]
Thanks for your PR @cristiandean! I was already working on a different branch with similar changes, please have a look and see if it fits your use cases!

**Comment by alinhle** [comment]
https://github.com/coralproject/talk/pull/2515

**Comment by cristiandean** [comment]
@cvle  For our case we still need the following classes:

`Tab-active` (For all places where there are tabs)
`UserBoxUnauthenticated`
`PostCommentFormFake`
`ReplyTo-root`
`ReplyTo-text`
`ReplyTo-username`
`ReplyTo-icon`

Do you think that makes sense?

Thank you

**Comment by alinhle** [comment]
@cristiandean I've added some changes to https://github.com/coralproject/talk/pull/2515:
- `Tab-active` can be selected similar to this example: 

```css
.coral-tabBarSecondary-tab[aria-selected=true] {
  background: red;    
}
```

- `UserBoxUnauthenticated`: Added a `.coral-unauthenticated` class and can be accessed through `.coral-unauthenticated .coral-viewerBox`
- `PostCommentFormFake`: Can be accessed through `.coral-unauthenticated .coral-createComment`

- `ReplyTo-X`: Added ReplyTo classes `.coral-createReplyComment-replyTo`, `.coral-createReplyComment-replyToText`, `.coral-createReplyComment-replyToUsername`. Icon can be selected by `.coral-createReplyComment-replyTo i` for now.

Wdyt?

**Comment by cristiandean** [comment]
Thank you very much @cvle! LGTM! =)

**Comment by alinhle** [comment]
Awesome!

**Pull request closed without merging**
