### PR TITLE
Spanish translation tweak #2 (& fix some breaking CSS)

### PR DESCRIPTION
**Pull request by kgardnr**
- Added translation support for "Edit" link for editing comments (`framework.edit` is the key)
- Added Spanish translation "Editar"
- Found some CSS contributed by this PR is actually breaking the comment box size, so I reverted it: https://github.com/coralproject/talk/pull/1990

### CODE REVIEW

**Comment by kgardnr** [comment]
Heads up to @snorremd, we had to revert that CSS, because it breaks the comment box when there is no avatar present - if you'd like to submit a new PR to address that, we'd be happy to review it!

**Review by wyattjoh — CHANGES_REQUESTED** [review]
Please revert the changes to the `yarn.lock` file. You'll need to upgrade your yarn version to resolve this issue going forward: https://yarnpkg.com/en/docs/install#mac-stable

**Comment by kgardnr** [comment]
@wyattjoh weird, I did upgrade yarn, it's cool I'll close this and create a new PR

**Comment by snorremd** [comment]
> Heads up to @snorremd, we had to revert that CSS, because it breaks the comment box when there is no avatar present - if you'd like to submit a new PR to address that, we'd be happy to review it!

I see, sorry about that. I will take another stab at it then.

**Pull request closed without merging**
