### PR TITLE
[CORL-1358] bios

### PR DESCRIPTION
**Pull request by tessalt**
## What does this PR do?

Adds support for commenter bios, which must be enabled through config. 

## What changes to the GraphQL/Database Schema does this PR introduce?

Adds new `settings.memberBios` config option on tenant, and `bio` field on users. 

## How do I test this PR?

- enable bios from Configuration -> General
- add a bio from stream by going to the preferences tab
- observe bio is visible when clicking on username in stream, in user drawer in admin.
- observe new "Bio is offensive or abusive" option for reporting a comment

### CODE REVIEW

**Comment by nick-funk** [comment]
We may need to set a max image width here haha

That or disable images because it looks like they aren't being wrapped in an iframe when they're embedded on the page

Also, giant Gandalf says hi

image

**Comment by nick-funk** [comment]
It looks like URL's are going to be problematic with the 100 character limit. Not sure whether we want to lengthen the limit or just not allow images.

image

**Review by nick-funk — CHANGES_REQUESTED** [review]
The code looks good, but I think there are some design considerations to run by Sam that may keep this from going out. See my previous comments for details on that. 😃

**Comment by tessalt** [comment]
@nick-funk I figured bios probably don't need links or images. I updated the markdown editor component to make the toolbar customizable and removed buttons we don't need.

**Review by kgardnr — APPROVED** [review]

**Review by nick-funk — APPROVED** [review]

**Review by wyattjoh — CHANGES_REQUESTED** [review]
This poses to much of a security risk, holding back for additional review.

**Comment by nick-funk** [comment]
@wyattjoh, I've replaced the RTE with a TextArea, have a look and tell me what you think

**Review by wyattjoh — APPROVED** [review]

**Pull request merged**
