### PR TITLE
Design pass tweaks 

### PR DESCRIPTION
**Pull request by okbel**
## What does this PR do?
Solves this list of issues https://www.pivotaltracker.com/story/show/137362063

### CODE REVIEW

**Comment by kgardnr** [comment]
2 things:
- [ ] Settings not showing for Commenter user
- [x] Cursor on usernames when they don't have bios

**Comment by okbel** [comment]
@kgardnr The settings thing turned out to be a BE thing. @wyattjoh it's working on it :) The cursor should be working. (If you don't have Bio, then your username it's not clickable. If you have a bio, you have a tiny triangle and it's clickable)

**Comment by kgardnr** [comment]
Excellent! Thanks @okbel!! :100:

**Comment by okbel** [comment]
@wyattjoh  I'm getting 
screen shot 2017-02-02 at 8 00 17 am


```js
TypeError: Cannot read property 'load' of undefined
    at comments (/Users/bel/Develop/talk/graph/resolvers/user.js:10:36)
    at resolveOrError (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:473:12)
    at resolveField (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:459:16)
    at /Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:273:18
    at Array.reduce (native)
    at executeFields (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:270:42)
    at completeObjectValue (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:688:10)
    at completeValue (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:597:12)
    at completeValueWithLocatedError (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:517:21)
    at completeValueCatchingError (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:493:21)
    at resolveField (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:461:10)
    at /Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:273:18
    at Array.reduce (native)
    at executeFields (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:270:42)
    at executeOperation (/Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:211:10)
    at /Users/bel/Develop/talk/node_modules/graphql/execution/execute.js:119:13
POST /api/v1/graph/ql 200 17.690 ms - -

```

When I hit settings. Any thoughts?

**Comment by okbel** [comment]
This is the query:


```
query myCommentHistory {
    me {
        comments {
            id
            body
            created_at
        }
    }
}
```

screen shot 2017-02-02 at 8 02 46 am

@wyattjoh

**Review by wyattjoh — APPROVED** [review]

**Pull request merged**
