### PR TITLE
Issue-676 add addOnBlur preventing loss of domain-whitelist settings

### PR DESCRIPTION
**Pull request by Goyapa**
## What does this PR do?
- set props `addOnBlur` true from the react-tagsinput 
- typed in domain-whitelist settings e.g. `localhost:3000 `will be set in Configure->Tech Settings->Permitted Domains 
- this address #676

## How do I test this PR?
- reset or maybe better remove Talk MongoDB database e.g.
```
> use talkdb
> db.dropDatabase()
```
- open http://localhost:3000/admin/install

- fill forms until point "3. Domain Whitelist"

- insert "localhost:3000" by typing, do not copy/paste nor hit the return Key!

- click button "Finish Install"

- open http://localhost:3000/admin/configure

- click "Tech Settings" and compare Permitted Domains

- verify the form shows `localhost:3000`

### CODE REVIEW

**Comment by kgardnr** [comment]
Thank you @Goyapa, welcome to your first Talk contribution! We will get this reviewed and merged for you :)

**Comment by alinhle** [comment]
@Goyapa Thanks, this is awesome. I totally agree with your reasoning. In fact I personally ran into this myself too and it would be great to have this change also in `client/coral-admin/src/routes/Configure/components/Wordlist.js` and `client/coral-admin/src/routes/Configure/components/Domainlist.js` too. Would you mind adding it to this PR?

**Comment by Goyapa** [comment]
Thank you @kgardnr and @cvle!

@cvle I had a view into 
`client/coral-admin/src/routes/Configure/components/Domainlist.js`
and tried to `addOnBlur true` there as well to get a concise behaviour over components as explained in #676.
But the UX was a bit confusing cause `/Domainlist.js` is implemented a little different than 
`client/coral-admin/src/routes/Install/components/Steps/PermittedDomainsStep.js`
and my change maybe breaks intended behavior, so I decided to commit only the one I was sure about.

I will have a deeper look into `client/coral-admin/src/routes/Configure/components/Domainlist.js` and `client/coral-admin/src/routes/Configure/components/Wordlist.js` too.

**Comment by alinhle** [comment]
@Goyapa I agree with you, I don't think we have an ideal solution at the moment. I'll bring this up today in our Scrum meeting and get some feedback. Thanks for your contribution!

**Review by alinhle — APPROVED** [review]
We talked about this in Scrum and we will follow your lead and unify our other TagInputs to look and behave exactly the same in a follow up PR. Thanks @Goyapa for your contribution!

**Pull request merged**
