### PR TITLE
[GDPR] Delete Account

### PR DESCRIPTION
**Pull request by wyattjoh**
## What does this PR do?

- Allows users to delete their own account and all associated data
  - Tombstones comments written by user
  - Removes author identifiable information from tombstone comments
  - Removes all actions by User
  - Removes User.

## How do I test this PR?

- TBD

### CODE REVIEW

**Comment by okbel** [comment]
@wyattjoh I'm currently working on this one. Could you check the merge conficts? I'm not sure with most of them. Thank you!

**Comment by kgardnr** [comment]
I get this error loading the stream:

delete_profile_stream

**Comment by okbel** [comment]
@kgardnr Try now! :)

**Comment by kgardnr** [comment]
@okbel @wyattjoh we should prevent a user from selecting Delete Account if they have an account deletion pending.

Steps to repro:
1. Click Delete Account
2. Follow steps
3. Get signed out
4. Sign back in
5. Go to My Profile
6. You can click Delete Account and go through steps again but you get an Unexpected Error

**Comment by kgardnr** [comment]
Also getting this error with a new local account - displays Unexpected Error on screen and below on server.

Steps to repro:
1. Register local account
2. Make a comment
3. Go to Delete Account
4. See error after inputting phrase and clicking Delete My Account 

```
TypeError: User.requestDeletion is not a function
    at requestAccountDeletion (/Users/kim/Projects/coral/talk/plugins/talk-plugin-profile-data/server/resolvers.js:9:41)
    at field.resolve (/Users/kim/Projects/coral/talk/graph/errorHandler.js:12:20)
    at resolveFieldValueOrError (/Users/kim/Projects/coral/talk/node_modules/graphql/execution/execute.js:501:12)
    at resolveField (/Users/kim/Projects/coral/talk/node_modules/graphql/execution/execute.js:465:16)
    at /Users/kim/Projects/coral/talk/node_modules/graphql/execution/execute.js:287:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)```

**Comment by kgardnr** [comment]
@okbel one small thing! Missing date in Account Deletion notice:

delete_account_notice

**Comment by kgardnr** [comment]
@wyattjoh found one more date to add and also organization email, on final step:

delete_account_time

**Review by kgardnr — APPROVED** [review]
Looks 💯 to me now!!!

**Pull request merged**
