### PR TITLE
CLI + Init fixes

### PR DESCRIPTION
**Pull request by wyattjoh**
## What does this PR do?

- Switches around init so that you must run `./bin/cli setup` in order to setup the application
- Consolidates settings
- Replaces prompt with a smoother lib
- Adds a `organizationName` setting to the `Settings` model

## How do I test this PR?

1. Flush db
2. Run `./bin/cli setup` and follow instructions

### CODE REVIEW

**Comment by okbel** [comment]
Looking good! 👍  Let me know when it's ready to be tested

**Comment by wyattjoh** [comment]
This introduced some e2e bugs, resolving and I'll ping you @okbel :)

**Review by okbel — CHANGES_REQUESTED** [review]
## Notes
This is perfect: `message:"settings not initialized, run ./bin/cli setup to setup the application first"` 👍 💯 


## Issues
1) When I try to use 'Belen' as displayName I get an error because of the B. Capitalized it's not allowed.
```js
? Display Name 
>> No special characters are allowed in a display name
```

2) I created an Admin and when I tried to log in I couldn't, I checked the db and:

screen shot 2017-01-30 at 11 07 06 pm


Then I set  `TALK_MONGO_URL=mongodb://localhost/coral-talk` and somehow it keeps failing.

Could it be pointing to another db?

@wyattjoh

**Comment by okbel** [comment]
Added some notes! @wyattjoh

**Comment by wyattjoh** [comment]
@okbel You may have not selected the role `ADMIN` via the space bar on that user create screen, so I'd check that.

The current implementation requires that special characters and upper case characters are not included, the BE already lowercases all the characters, but the CLI assumes that you know what you're doing, so it doesn't try and conform your input.

**Comment by okbel** [comment]
Sorry. I pasted a non-admin user. Here I did the whole flow again. Maybe I'm pointing  to another db? Also, If it's a user that does not have a role I should still be able to login, right? Isn't it commenter user?

screen shot 2017-01-31 at 8 06 10 am
screen shot 2017-01-31 at 8 06 53 am
screen shot 2017-01-31 at 8 06 21 am 1

@wyattjoh

**Comment by wyattjoh** [comment]
@okbel I just flushed my databases, and followed this procedure:

```bash
./bin/cli -c .env setup

# answered questions

./bin/cli -c .env users create

# answered questions

npm run dev-start
```

And I was able to login as the user that I created. I need you to post the server logs if you are still experiencing a login issue with `DEBUG=*` otherwise I won't be able to debug.

**Review by okbel — APPROVED** [review]

**Comment by okbel** [comment]
Awesome! I flushed them all and it works perfect :))))) 👍

**Pull request merged**
