### PR TITLE
[CORL-595] move notification settings update button

### PR DESCRIPTION
**Pull request by tessalt**
## What does this PR do?
- moves "update" button to bottom of notifications settings form (was previously floated to the right)

### CODE REVIEW

**Comment by nick-funk** [comment]
I could be wrong, but I think the placement might have been more like this rather than at the very bottom.

image

Making it just aligned under the header and floated right makes it part of that area without forcing it directly underneath the other control items.

Please note, the underline is just for alignment demonstration, I don't think they want a horizontal rule under the header title.

**Comment by tessalt** [comment]
@nick-funk ohh i thought we decided on underneath?

**Comment by nick-funk** [comment]
> @nick-funk ohh i thought we decided on underneath?

I'm not sure anymore. I remember discussing this with Sam and she thought it was a good idea the way I've suggested.

She could have changed her mind and I could be completely wrong on this.

**Comment by tessalt** [comment]
@nick-funk your solution makes more sense wrt the jira ticket 👍

**Comment by tessalt** [comment]
@nick-funk updated to match your illustration!

**Review by nick-funk — APPROVED** [review]

**Review by wyattjoh — APPROVED** [review]

**Pull request merged**
