### PR TITLE
Admin actions for Flagged comments

### PR DESCRIPTION
**Pull request by okbel**
## What does this PR do?
- Adds Admin actions for Flagged comments
- Changes `null` for `NONE`
- Solves the Flag Queue issue. It returns only `NONE` or `PREMOD` statuses for flagged comments.
- Old routes, and old actions clean up. (`/comments` endpoint free)

## How do I test this PR? 

- Flag a comment
- Go to Moderation 
- Check the actions for flagged comments

### CODE REVIEW

**Comment by jde** [comment]
Comments are remaining in the flag queue after being ACCEPTED. 

The flag queue should not show comments that have already been acted on by a moderator (aka, ACCEPTED or REJECTED)

**Review by jde — CHANGES_REQUESTED** [review]
Comments are remaining in the flag queue after being ACCEPTED.

The flag queue should not show comments that have already been acted on by a moderator (aka, ACCEPTED or REJECTED)

**Comment by jde** [comment]
Also, in a related issue, I'm seeing rejected comments in the All list. The All list should only show comments that need moderator attention (those in the Premod and Flagged lists). 

Sorry this is confusing and not well documented. Design is working on making this section clearer.

**Comment by okbel** [comment]
@jde The 'All Queue' was removed after a Design Meeting until further research is completed. (It wasn't updated to master)

About the comments that have been `ACCEPTED ` or `REJECTED` showing in the Flagged Queue. I'm working on a workaround for this https://github.com/apollographql/graphql-tag/issues/47 since I need to perform a `statuses: [null, PREMOD]` and I'm getting an error because of null. (Only happens on the FE. The Query is valid)

**Comment by okbel** [comment]
Updated and ready to be tested! (Description updated too) Super thanks to @wyattjoh who addressed this super quickly. Also, we removed all the actions  with `/comments` endpoints involved, and some old routes! 

@jde

**Review by jde — APPROVED** [review]

**Pull request merged**
