### PR TITLE
Adds status field to the asset and changeStatus

### PR DESCRIPTION
**Pull request by gabelula**
## What does this PR do?

- Adds status field to the Asset model
- Adds changeStatus method to the Asset model
- It changes the endpoint to change status to use that new method
- Adds tests

## How do I test this PR?

- Check that the stream gets closed and open and that it works.

### CODE REVIEW

**Review by impronunciable — COMMENTED** [review]
looks good

**Comment by gabelula** [comment]
This is still relevant as we do not have backend for the status.

**Comment by wyattjoh** [comment]
The closed status of the asset is fully represented by the closedAt field, so i don't see the point of this as it seems like we are duplicating effort.

**Comment by wyattjoh** [comment]
See this PR https://github.com/coralproject/talk/pull/134 for the closed at field which provides the Opened/Closed status.

**Pull request closed without merging**
