### PR TITLE
Integrate admin into GraphQL framework

### PR DESCRIPTION
**Pull request by alinhle**
## What does this PR do?
- Integrate admin into the GraphQL framework
- Includes some refactoring and cleanups.
- Some naming harmonisation for Queries, Mutations and Fragments.

### Naming Scheme

The naming scheme I follow is:

_Queries:_
prefix_name, e.g. `CoralAdmin_Community`

_Mutations:_
(no prefixing if the mutation is just a 1:1 mapping of a mutation from the schema).
mutationName, e.g. `SetCommentStatus`

_Fragments:_
prefix_name_part, e.g. `CoralAdmin_Comment_root`

### CODE REVIEW

**Review by riley — APPROVED** [review]
The only thing I would do is add your renaming scheme to the description of this PR for posterity. Otherwise, what an epic refactor! 💯

**Comment by alinhle** [comment]
Added the naming scheme to the description.

**Comment by cvle** [comment]
Please don't merge this before the translation refactor. I want to resolve the merge conflicts here instead of in the other PR.

**Comment by alinhle** [comment]
I'm fixing the bugs, from the merge with the graphql error handling PR.

**Comment by alinhle** [comment]
Done

**Pull request merged**
