### PR TITLE
User integration

### PR DESCRIPTION
**Pull request by davidgljay**
## What does this PR do?

Integrates user information into comments and actions.

## How do I test this PR?

1. Open the comment stream.
2. You should not be able to like or flag.
3. Log in.
4. You should be able to post a comment. This comment should have the right name.
5. Like and flag a comment.
6. Check admin panel, the post requests to the server should include your user id.
7. Click the "Reply" button on a reply. The reply box should open on the parent comment.
8. Create a stream with several comments and replies. Like buttons should still work.
9. Click the "flag" button and reload the page. The like count on that comment should be unchanged.
10. Post a comment. The notification should not cover the last comment in the stream.

@coralproject/tech

### CODE REVIEW

**Comment by gabelula** [comment]
The moderation queue still has 'Anonymous' for all the user names.

**Comment by riley** [comment]
I can't flag a second comment after I test flagged the first one.

**Comment by davidgljay** [comment]
@riley: I tried a few different combinations but couldn't reproduce this flagging error. Can you give more details?

**Comment by gabelula** [comment]
Is it ok to be able to flag a comment that you already liked?

**Comment by losowsky** [comment]
@gabelula yes

**Comment by gabelula** [comment]
Is ok to be able to like and/or flag my own comment?

**Comment by gabelula** [comment]
@davidgljay Can you change it so I can't flag or like my own comment?

**Comment by davidgljay** [comment]
@gaba We haven't had a user story for not being able to like or flag one's own comment. I can put it in as a separate PR, but let's not block these bugfixes for it.

**Review by gabelula — APPROVED** [review]
It looks good.

**Pull request merged**
