### PR TITLE
Arabic Translation

### PR DESCRIPTION
**Pull request by memz**
What does this PR do?

This PR adds Arabic translations to the main locale file and most plugins.

### CODE REVIEW

**Comment by kgardnr** [comment]
Thank you @memz! We're so happy you contributed this - awesome!

**Review by kgardnr — APPROVED** [review]

**Comment by memz** [comment]
You are most welcome @kgardnr !

**Comment by kgardnr** [comment]
Which website will you be using Talk on @memz? We would love to showcase it when you launch :)

**Comment by memz** [comment]
can't say now @kgardnr before we go live :)

**Pull request merged**
