### PR TITLE
Added env variable TALK_DEFAULT_LANG

### PR DESCRIPTION
**Pull request by PepeFranco**
## What does this PR do?

Solves issue #1041 

## How do I test this PR?
Add env variable TALK_DEFAULT_LAN with the desired default locale. Build and check it is running now in that locale by default.

### CODE REVIEW

**Review by wyattjoh — CHANGES_REQUESTED** [review]
If you can change `TALK_DEFAULT_LAN` to `TALK_DEFAULT_LANG` that would be awesome 😄

**Comment by PepeFranco** [comment]
Done!

**Review by wyattjoh — APPROVED** [review]
Looks great to me!

**Comment by kgardnr** [comment]
Nicely done @PepeFranco!

**Pull request merged**
