### PR TITLE
[CORL-2920]: Community table fallbacks alignment updates

### PR DESCRIPTION
**Pull request by kabeaty**
## What does this PR do?

These changes update the styles for the community table in the admin so that all user data is displayed with the desired alignment.

If a username isn't available, the fallback message in this case should still be left aligned. All other columns should have their data vertically aligned in the middle, including the email data and its fallback message, member since, role, and status data.

## These changes will impact:

- [ ] commenters
- [x] moderators
- [x] admins
- [ ] developers

## What changes to the GraphQL/Database Schema does this PR introduce?

none

## Does this PR introduce any new environment variables or feature flags?

no

## If any indexes were added, were they added to `INDEXES.md`?

n/a

## How do I test this PR?

Go to the `Community` tab in the admin. If a username isn't available, the fallback message in this case should be left aligned. All other columns should have their data vertically aligned in the middle, including the email data and its fallback message, member since, role, and status data. (You can either update data so no username/email is available, or just comment out parts of the code that show the username/email so that the fallback shows)

### CODE REVIEW

**Review by nick-funk — APPROVED** [review]
Looks good! ✅

**Review by marcushaddon — COMMENTED** [review]
I'm seeing the fallback message for username left aligned, but I also see the other columns being left aligned, rather than in the center, which is what I understood from the PR description as the requirement. Should they be in the middle?

**Comment by kabeaty** [comment]
> I'm seeing the fallback message for username left aligned, but I also see the other columns being left aligned, rather than in the center, which is what I understood from the PR description as the requirement. Should they be in the middle?

The other columns should still be left aligned. The requirement is that all columns then also have their data **vertically** centered, in addition to their horizontal left alignment.

**Comment by marcushaddon** [comment]
> > I'm seeing the fallback message for username left aligned, but I also see the other columns being left aligned, rather than in the center, which is what I understood from the PR description as the requirement. Should they be in the middle?
> 
> The other columns should still be left aligned. The requirement is that all columns then also have their data **vertically** centered, in addition to their horizontal left alignment.

Ah that makes sense.

**Review by marcushaddon — APPROVED** [review]

**Pull request merged**
