### PR TITLE
Introduce final form, i18n helper, validators and refactor AddEmailAddress

### PR DESCRIPTION
**Pull request by alinhle**
## What does this PR do?
- Introduce https://github.com/final-form/react-final-form
- Refactor `AddEmailAddress` of `talk-plugin-local-auth`
- https://www.pivotaltracker.com/story/show/157413675
- https://www.pivotaltracker.com/story/show/157570952
- Adds a i18n helper cli

```
# ./scripts/i18n.js -h

  Usage: i18n [options] [command]

  Tools to help manage i18n locales.
  Currently this is limited to top level locales excluding the plugin locales.

  Options:

    -V, --version               output the version number
    -h, --help                  output usage information

  Commands:

    sort                        Sort keys of all locales in alphabetical order
    delete <path>               Delete key at path in all locales
    copy [options] <from> <to>  Copy translation from one key to another
    drop-unused                 Drop translations that are not present in the en.js locale
```

- Sort, ands remove some unused translation keys

## How do I test this PR?
- Use social login to create a user

### CODE REVIEW

**Comment by okbel** [comment]
Code looks 💯 This is a really good update. Good job!

**Comment by okbel** [comment]
We should consider writing an example of how to build forms, at least a minimal example

**Comment by kgardnr** [comment]
I like @okbel's idea of including a form example - @cvle can you add it to our docs??

**Comment by kgardnr** [comment]
@cvle I can't test this until we can update from master, because of the social login bug that's fixed there

**Comment by alinhle** [comment]
I'll fix the conflicting files, right after the #1523 PR is merged.

**Review by kgardnr — APPROVED** [review]
LGTM! I'll wait for @okbel to give the ok before we merge 💯

**Review by okbel — APPROVED** [review]

**Pull request merged**
