### PR TITLE
[GDPR] Username Change

### PR DESCRIPTION
**Pull request by wyattjoh**
## What does this PR do?

Adds support for a user to change their own username without forcing the username moderation flow.

## How do I test this PR?

- TBD

### CODE REVIEW

**Comment by kgardnr** [comment]
A few issues here:

1. Unit tests are failing
2. On username change saving, I get "Unexpected error" and this:

error_username

**Review by kgardnr — CHANGES_REQUESTED** [review]
See comment

**Comment by okbel** [comment]
This one is ready to be checked! @kgardnr @cvle

**Comment by kgardnr** [comment]
There's an issue with the timer - I create a new user, and I think the timer is started and won't let me change my name for 14 days. This is what's shown in the error.

**Review by kgardnr — APPROVED** [review]

**Pull request merged**
