### PR TITLE
undo reject comment

### PR DESCRIPTION
**Pull request by devonjs**
## What does this PR do?
Adds ability to undo rejection of a comment

## How do I test this PR?

- reject a comment
- see confirmation of rejection with undo link
- click undo and see comment come back

## Additional notes
Currently this does not disappear over time, until you navigate away or click 'undo'.  Let me know your thoughts on this one, figured we could allow the user to undo at any time after rejection.

### CODE REVIEW

**Comment by kgardnr** [comment]
Oooo awesome @devonJS thank you! We will review this early next week for ya! 😎

**Review by kgardnr — APPROVED** [review]
Feature works perfectly! Once @okbel and/or @cvle give the thumbs up on the code review, we can merge it! 👍

**Comment by kgardnr** [comment]
Fixes #1047

**Comment by kgardnr** [comment]
Hey @devonJS sorry for the confusion, it was my mistake - this is supposed to be applied to the Comment Stream in-stream moderation, not to the moderation queues. Would you mind updating the PR to reflect that? Could you also create a branch on your remote repo instead of cutting it directly from master too? Thanks!

**Review by kgardnr — CHANGES_REQUESTED** [review]
Needs to be applied to comment stream, not the admin mod queues.

**Comment by devonjs** [comment]
@kgardnr sure will take a look this week

**Comment by devonjs** [comment]
@kgardnr updated with new PR (from feature branch in my forked version) #1149 

I was thinking about it, if we have undo capabilities in-stream, would you guys potentially want to mimic that feature in the moderation queue as well?  Partly don't want this code to go to waste heh :P

**Comment by kgardnr** [comment]
Thanks @devonJS! Yes you're right. I'm going to close the PR for now, but we will review with our product and design team and get back to you 🥇

**Pull request closed without merging**
