### PR TITLE
Embed Stream refactor

### PR DESCRIPTION
**Pull request by alinhle**
This is a first step to add support for extendable queries.

## What does this PR do?
- Move `components` into a separate folder.
- Add `reducers`, `actions` and `constants` to the embed in order to manage UI state
- Split `Embed ` component into a `presentational component` and a `container`
- Put `activeReplyBox` into `Redux`
- Simplify `countCache` as `commentCountCache` and put it in the local embed reducer.
- Remove stale props from `ConfigureStreamContainer` and `ProfileContainer`
- Let `ConfigureStreamContainer` and `ProfileContainer` retrieve their own props from store instead from `Embed`.

## How do I test this PR?

- Check that everything in the embed still works as before.

### CODE REVIEW

**Comment by riley** [comment]
I'm unable to post a comment in the stream:

screen shot 2017-04-18 at 11 38 16 am

the comment doesn't show up in the pre-mod queue or anything, it just disappears

**Comment by alinhle** [comment]
That's weird. I can't reproduce and also `CreateCommentInput` is defined in the servers `typeDefs.graphql` which I didn't touch.

**Comment by riley** [comment]
I restarted the build and the server, and I'm still getting it. Do I need to do `yarn` or something to get dependencies? Also, I'm on `localhost:3000` and not an asset page. I don't know if that matters.

**Comment by okbel** [comment]
@cvle Could you solve the merge conflicts?

We should merge this one and then add more slots.

**Comment by alinhle** [comment]
This PR is outdated. New PR coming soon.

**Pull request closed without merging**
