### PR TITLE
Admin section filter

### PR DESCRIPTION
**Pull request by cristiandean**
## What does this PR do?
Add section button to admin stories page to search keywords.

## How do I test this PR?
Stories with section meta will show a button:

Screen Shot 2020-04-03 at 14 16 49

Screen Shot 2020-04-03 at 14 17 58

### CODE REVIEW

**Comment by kgardnr** [comment]
Hey @cristiandean we really love this idea. I'm going to have our designer take a pass on it.

I was wondering - what do you think about being able to filter Moderation queues by section?

**Comment by cristiandean** [comment]
It would be great for us ❤️! Our newsroom is large and we have a huge amount of articles posted daily. If we could filter the moderation queues by section it would make life easier for our moderators who moderate specific sections.

**Comment by kgardnr** [comment]
Ok great @cristiandean, I'm gonna put the review on this PR on hold until our team can have a conversation about this! Will get back to you by next week <3

**Comment by wyattjoh** [comment]
Thanks @cristiandean for the work!

After reviewing the implementation, we probably want to take a deeper dive into managing sections in general as there are a few problems:

- Sections are currently being filtered with use of the `query` which just uses the text index against all sections, this isn't going to return what you're looking for with something like `Cooking` where a description or title might also include the word
- Situations involving multiple sections still is not supported

At this moment, I'm going to close this until we have a chance to take a pass on it.

**Pull request closed without merging**
