### PR TITLE
Optional websocket support

### PR DESCRIPTION
**Pull request by cristiandean**
## What does this PR do?
Allows that websocket become optional maintaining the behavior as possible. As discussed in this issue #1615  we are going to lose freshness in favor of network stability. We would like know your oppinion about this Pull Request.

## How do I test this PR?
Set **TALK_WEBSOCKET_CLIENT_DISABLE=TRUE**

### CODE REVIEW

**Comment by hjanuschka** [comment]
i love this! ❤️  thx for starting it, and putting in your time.
how about a client side refresh using REST in an interval?


getting rid of websockets, i guess would eliminate alot of hw resources at our end.

**Comment by kgardnr** [comment]
Hey @cristiandean and @hjanuschka - we've taken a look at this and it's not a full implementation of disabling websockets - since websockets are so core to Talk 4.x, this might be difficult to do fully.

We're looking at alternatives for 5.x, and will keep you posted.

I would suggest testing this patch in a production environment and seeing if it solves the issues you're facing. We cannot merge this into core as-is, without more extensive testing in a live environment. We'd be interested to see what comes of your testing. Please report back!

**Comment by hjanuschka** [comment]
since our infra. is now able to handle the amount of websockets, and we are probably soon moving the websockets to akamai anyway - we do not really need it.

i would like to test it anyway, but we'd need a sort of `setInterval` alternative to get a bit of freshness atleast.


oh and keep WS in admin dashboard.

**Comment by wyattjoh** [comment]
Sounds great @hjanuschka! Feel free to patch your version to play with websocket support in Talk 4, we plan on focusing first class support of websocket toggling for the embed stream in Talk 5.

**Pull request closed without merging**
