### PR TITLE
User Badges Styling Fix

### PR DESCRIPTION
**Pull request by okbel**
## What does this PR do?
- Adds styling fix for user badges.

out

### CODE REVIEW

**Comment by theysamtheirs** [comment]
image

Featured tag no longer is right aligned with this update.

**Comment by theysamtheirs** [comment]
#### Updates for Badge Styles and Margins
image


badge style update for mobile:

.talk-plugin-tag-label {
    padding: 2px 6px;
    _remove font-weight: bold;_
}

updated margins (not sure how/where this lives):
image

**Comment by okbel** [comment]
Ready! Changes added! Thanks you!

**Review by kgardnr — DISMISSED** [review]
Looks great to me! 💯

**Comment by alinhle** [comment]
The only thing that bugs me is that between the `Staff` tag label and the `commentAuthorTags` Slot the margin changes. When it's full size the margin between those is `3px`, when it's smaller size the margin becomes `0px`.

**Review by alinhle — CHANGES_REQUESTED** [review]
The margin between `Staff` label and `commentAuthorTags` Slot should not change.

**Comment by okbel** [comment]
Updated!

**Comment by kgardnr** [comment]
@IAmSamHankins @okbel see what happens with the timestamp on threads:

timestamp

**Review by kgardnr — APPROVED** [review]

**Review by alinhle — APPROVED** [review]

**Pull request merged**
