### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by mkonikov**
## How do I test this PR?

- click a button
- view the cat
- see the cat meow

### CODE REVIEW

**Comment by kgardnr** [comment]
Great catch! Added one comment for you @mkonikov!

**Comment by mkonikov** [comment]
Fixed in that other PR

**Comment by kgardnr** [comment]
Thanks @mkonikov! This is a dupe PR right? I'll just close it :)

**Comment by mkonikov** [comment]
@kgardnr I didn't mean to make it two separate PRs but it's not a dupe. Same typos are in the comments in the Google Auth plugin. This fixes them.

**Comment by kgardnr** [comment]
Oh I see -- thanks @mkonikov! In the future if you could add a small description to your PRs, it makes it more clear.

**Review by kgardnr — APPROVED** [review]

**Pull request merged**
