### PR TITLE
Standardizes errors for API error returns

### LINKED ISSUE #220: Clicking on Settings tab and then clicking back to Comments tab, sets Stream closed and the setting is `null`
### Expected behavior
Clicking different tabs if the stream is set to Open - you should be able to comment, take actions, see your history, and see settings (if you have appropriate permissions)

### Actual behavior
Clicking on Settings and then back to Comments, seems to clear the Settings which results in the stream being Closed.

### Steps to reproduce behavior
1. Go to comment stream, click on Settings, click back to Comments
2. Can't comment or reply (get 500)
3. Go to Settings, re-open stream, all works as expected

### PR DESCRIPTION
**Pull request by wyattjoh**
## What does this PR do?

Standardizes errors in new [`errors.js`](https://github.com/coralproject/talk/blob/6e89734e127b16976aea04455da36d745f712008/errors.js).

## How do I test this PR?

- Run tests
- Create a comment
- Copy network request for creating a comment as a CURL request
- Close comment stream
- Run command as CURL
- Notice non-null message field on error returned

Closes #220.

### CODE REVIEW

**Comment by okbel** [comment]
```bash
▼  talk git:(topic-220) curl 'http://localhost:3000/api/v1/comments' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate, br' -H 'x-csrf-token: lN1aEuOi-_w1PZgcRX6w7MiCCesOFhY_3HlA' -H 'Accept-Language: en-US,en;q=0.8,es-419;q=0.6,es;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:3000/embed/stream?initialWidth=500&childId=coralStreamEmbed&parentTitle=Coral%20Talk&parentUrl=http%3A%2F%2Flocalhost%3A3000%2F' -H 'Cookie: talk.sid=s%3AtjSyFDZvQ4Zr2rk4_21EtKQEMVCSz2Qt.HvwzxHgh6Xq%2FIdg9K3ekmxdSrYs%2FxO7c09r3ApqjvgI' -H 'Connection: keep-alive' --data-binary '{"body":"asd","asset_id":"9b9ccbd6-dfae-405e-896f-5fc62af5556c","author_id":"923661aa-bc44-4f5c-b05e-8ac6cf84e5ad"}' --compressed
{"message":"asset commenting is closed","error":{"message":"asset commenting is closed","status":400,"translation_key":null,"metadata":{"closedMessage":null}}}%                                          ▼  talk git:(topic-220) 

```

**Comment by okbel** [comment]
I'm getting this: 

```bash
▼  talk git:(topic-220) curl 'http://localhost:3000/api/v1/comments' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate, br' -H 'x-csrf-token: lN1aEuOi-_w1PZgcRX6w7MiCCesOFhY_3HlA' -H 'Accept-Language: en-US,en;q=0.8,es-419;q=0.6,es;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:3000/embed/stream?initialWidth=500&childId=coralStreamEmbed&parentTitle=Coral%20Talk&parentUrl=http%3A%2F%2Flocalhost%3A3000%2F' -H 'Cookie: talk.sid=s%3AtjSyFDZvQ4Zr2rk4_21EtKQEMVCSz2Qt.HvwzxHgh6Xq%2FIdg9K3ekmxdSrYs%2FxO7c09r3ApqjvgI' -H 'Connection: keep-alive' --data-binary '{"body":"asd","asset_id":"9b9ccbd6-dfae-405e-896f-5fc62af5556c","author_id":"923661aa-bc44-4f5c-b05e-8ac6cf84e5ad"}' --compressed
{"message":"asset commenting is closed","error":{"message":"asset commenting is closed","status":400,"translation_key":null,"metadata":{"closedMessage":null}}}%                                          ▼  talk git:(topic-220) 

```

Is this correct? The code looks 💯

**Comment by okbel** [comment]
@wyattjoh

**Comment by wyattjoh** [comment]
That message is correct, the previous response was:

```json
{"message": "asset has commenting closed because: null"}
```

So this is a lot more explicit @okbel.

**Comment by okbel** [comment]
Awesome! Terrific work!

**Review by okbel — APPROVED** [review]

**Pull request merged**
