### PR TITLE
Linting Error

### PR DESCRIPTION
**Pull request by okbel**
## What does this PR do?
This PR solves  ` 6:3  error  Don't use process.exit(); throw an error instead  no-process-exit`linting error
## How do I test this PR?

- Run `npm run lint`
- It shouldn't trigger any errors

@coralproject/tech

### CODE REVIEW

**Comment by wyattjoh** [comment]
Why not we actually throw an error instead of disabling the linting rule?

**Comment by okbel** [comment]
I'm in favor of doing that. Like the mongo connection. I thought this was a blocker! Working on it.

**Comment by okbel** [comment]
@wyattjoh Updated and passing!

**Review by gabelula — APPROVED** [review]
It seems good.

**Pull request merged**
