### PR TITLE
Unique username

### PR DESCRIPTION
**Pull request by gabelula**
## What does this PR do?

Change the User model to have a unique username.

## How do I test this PR?

- Register a first user
- Register a second user with the same display name than the first
- Check the error

### CODE REVIEW

**Comment by davidgljay** [comment]
@gaba I tried registering multiple users with the display name "David" and received no error.

**Review by davidgljay — CHANGES_REQUESTED** [review]
I was able to register multiple users with the same displayName:

```
{
	"_id" : ObjectId("58757e9245201872ea91f429"),
	"updated_at" : ISODate("2017-01-11T00:38:42.936Z"),
	"created_at" : ISODate("2017-01-11T00:38:42.936Z"),
	"displayName" : "David",
	"password" : "$2a$10$vE1ItFL8Jqtacye36b7RGufZ5Qxva6pjdq9Ist1afeoDHZsQZExNO",
	"settings" : {
		"bio" : ""
	},
	"status" : "active",
	"roles" : [ ],
	"profiles" : [
		{
			"id" : "dj4@gmail.com",
			"provider" : "local"
		}
	],
	"id" : "9b7eac2a-d3ab-4e9b-8f43-b9045c64da4a",
	"__v" : 0
}
{
	"_id" : ObjectId("58757eaa45201872ea91f42a"),
	"updated_at" : ISODate("2017-01-11T00:39:06.210Z"),
	"created_at" : ISODate("2017-01-11T00:39:06.210Z"),
	"displayName" : "David",
	"password" : "$2a$10$xym8KwgWmeVDu2yTHplCduMypTMPPg53I2y0mHBtV6BYAYQxFSmwa",
	"settings" : {
		"bio" : ""
	},
	"status" : "active",
	"roles" : [ ],
	"profiles" : [
		{
			"id" : "dj5@gmail.com",
			"provider" : "local"
		}
	],
	"id" : "5425c444-7c9a-455b-bdb6-973b1b7dd676",
	"__v" : 0
}
```

**Comment by gabelula** [comment]
@davidgljay Which endpoint were you using to create the users?

**Review by davidgljay — CHANGES_REQUESTED** [review]
Works! Currently the error returned to the frontend is blank, it would be good to return an error string so that we can display the failure to the user (right not it just says "error.500"). Otherwise this is good.

**Review by davidgljay — APPROVED** [review]

**Pull request merged**
