### PR TITLE
E2e browserstack

### PR DESCRIPTION
**Pull request by alinhle**
## What does this PR do?
- Integrate Nightwatch and Browserstack for e2e

## How to run tests with BrowserStack

- Run `yarn e2e-browserstack` and use the following ENV variables to configure:
  - `BROWSERSTACK_USER` – defaults to `coralproject2`
  - `BROWSERSTACK_KEY` – required

### Run specific browser on browserstack
  - `BROWSERSTACK_KEY=xxx yarn e2e-browserstack -- --env firefox`

## Local Tests
This PR adds `selenium-standalone` and does not installs it until you run `yarn e2e`. This is useful when you do not want to use BrowserStack and you want to run them on your own instead of tunneling an instance.

### Requirements
- Java >= 8
- Chrome

### How to run local tests 
`yarn e2e`

### How to run local tests in headless mode
`yarn e2e -- --env chrome-headless`

## CircleCI

- Pull Request will run a local e2e using headless chrome
- When merging to master, CI will run e2e using browserstack

## Test Coverage 
- Basic Functionality for the Embed Stream
- Install Tests
- Admin Tests (on progress)

# TODO
- ~Port tests from https://github.com/coralproject/talk/pull/998~
- ~Start tests with a separate clean db.~
- ~Integrate with CI~

### CODE REVIEW

**Comment by wyattjoh** [comment]
Useful: https://www.browserstack.com/automate/continuous-integration

**Comment by okbel** [comment]
Updated Readme!

**Comment by okbel** [comment]
Ready to be tested @cvle!

**Comment by okbel** [comment]
The output now should be like this:

screen shot 2017-10-18 at 8 08 18 am

**Review by okbel — APPROVED** [review]

**Review by wyattjoh — APPROVED** [review]

**Pull request merged**
