### PR TITLE
Added whitelist question to cli-setup

### PR DESCRIPTION
**Pull request by wyattjoh**
## What does this PR do?

Adds questions related to adding to the domain whitelist via the cli.

### CODE REVIEW

**Comment by jtnelson** [comment]
@wyattjoh Choosing "No" for adding whitelisted domains doesn't validate correctly

image

**Comment by jtnelson** [comment]
@wyattjoh Password validation no longer works

image

**Review by jtnelson — CHANGES_REQUESTED** [review]
See comments about validation errors.

**Comment by wyattjoh** [comment]
Related to the password error, you need to update your dependencies with "yarn". The other one is a but and should be patched.

**Review by jtnelson — APPROVED** [review]
👍

**Pull request merged**
