### PR TITLE
Admin user details translations and wording

### PR DESCRIPTION
**Pull request by leeeandroo**
## What does this PR do?
Add translation keys on `UserDetails` and `ViewOptions` components to Admin. Also change E-mail to Identification and icon and show the provider to make it consistence when user register using Facebook.

## How do I test this PR?

- Setup your talk with `TALK_FACEBOOK_APP_ID` and `TALK_FACEBOOK_APP_SECRET`
- Create an `local` user and a `facebook` user
- Do some comments whit each user 
- Access Admin and click on the username
- See the translations and Identification field with new icon and provider (`local` or `facebook`)
- Check the Admin sidebar `View Options`

### CODE REVIEW

**Comment by kgardnr** [comment]
Hi @leeeandroo, changing this

`{t('user_detail.identification')} ({provider})` 

is outside the scope of adding the translation keys. Can you use this PR to add the missing translation keys as they currently are, and then we can take under review whether we would like to make the product decision to revise the above? Thanks!

**Comment by leeeandroo** [comment]
Hi @kgardnr ,

Sorry the delayed answer. I've changed it, could you have a look again?

How to proceed about the `identification` changes? Do I need to open another PR for it or an issue?

Thanks,

**Comment by kgardnr** [comment]
Thanks @leeeandroo! We will review this.

For the identification stuff, we're doing a refactor of our auth, so let's wait until after that's merged, and then we can do another pass on what this is trying to solve here. Is that cool?

**Comment by leeeandroo** [comment]
Yes, that's ok! 

Thank you :)

**Review by kgardnr — APPROVED** [review]

**Pull request merged**
