### PR TITLE
Plugin social share

### PR DESCRIPTION
**Pull request by leeeandroo**
## What does this PR do?
Create a plugin to share comments on **Facebook** and **Twitter**.
Its supposed to fix this #1026.

As I'm using a `react-share` package, It's possible to use other social media and we can think about a way to enable/disable providers.
btw, I'm open to suggestions :)

## How do I test this PR?

- Add the new plugin `talk-plugin-social-share` to your `plugins.json` 
- Run the Talk and check the new share option on embed stream.
- Try to share on Twitter
- Try to share on Facebook (does not work on localhost, just with a online `asset_url`)

### CODE REVIEW

**Comment by kgardnr** [comment]
Hey @leeeandroo! Thank you so much for submitting this! We've reviewed it and we have some feedback.

We will share this with you next week!

**Comment by kgardnr** [comment]
Hey @leeeandroo, sorry for the delay here. We think the best way to incorporate this with the existing Permalink/Share button is to combine these into one slot and therefore one place for a commenter or reader to take action.

We're not sure yet how we want to tackle that within the plugin universe yet - we'll get back to you next week!

**Comment by kgardnr** [comment]
Hi @leeeandroo apologies for the delay getting back to you here!

We've decided we need to start being able to include external plugins (so not hosting all plugins within the core plugins folder). We also want to credit those in the community who are contributing plugins :)

Can you create this as a repo on your own Github (or on your organization's), and we will add it to our plugin directory?

**Comment by kgardnr** [comment]
Oh and you can also publish it to npm, so it's even easier for others to use :) Thanks Leandro, you're the best!

I'm going to close this PR then too fyi

**Comment by leeeandroo** [comment]
Hi Kim.

Thank you, I'll release it and I let you know!

Best,

2018-03-21 22:42 GMT+01:00 Kim Gardner <notifications@github.com>:

**Comment by kgardnr** [comment]
Great! Thanks @leeeandroo!

**Pull request closed without merging**
