### PR TITLE
Added refetch button to the "Stories" tab in the admin

### PR DESCRIPTION
**Pull request by jqueryisamonad**
## What does this PR do?
Issue #1948 

## How do I test this PR?

- Go to the "Stories" tab in the admin
- Filter streams by "Open" status
- Change any stream status ("Open" -> "Closed")
- Status has changed, but the list has not been updated
- Click to "Refetch assets"

### CODE REVIEW

**Review by kgardnr — CHANGES_REQUESTED** [review]
Hey @hovoodd this is a great start! The part missing is that button shouldn't just refetch the assets that exist - it should actually rescrape the assets and their metadata. You can see this in the scraper service. Let us know if you have questions!

**Comment by kgardnr** [comment]
Hey @hovoodd let us know if you have questions around my previous comment - thank you so much! 😸

**Comment by jqueryisamonad** [comment]
@kgardnr hi, I think I've done, but there's one question.

We still should refetch all data after scrape, right? 🤔

**Comment by kgardnr** [comment]
Hey @hovoodd yes! We should rescrape any data that we originally scrape.

**Pull request closed without merging**
