### PR TITLE
[CORL-1199] Show nice error message on network time out

### PR DESCRIPTION
**Pull request by nick-funk**
## What does this PR do?

Shows "Network error. Please refresh your page and try again." when the retry middleware times out from too many attempts on failed/timed out requests.

## What changes to the GraphQL/Database Schema does this PR introduce?

None

## How do I test this PR?

- Add the following function above `retrieveCommentConnection` in `comment.ts` (line 655)

```
function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
```

- Inside of `retrieveCommentConnection`, before `return retrieveConnection(input, query);` (line 668) put the following:

```
await sleep(60000);
```

- Load up the stream and wait for the error to show up inside a nice callout.

Note: you can use the `sleep` function to time out any request you want, feel free to test the other query renderer's that have this network error check implemented.

### CODE REVIEW

**Comment by wyattjoh** [comment]
After adding the following to the app:

```diff
diff --git a/src/core/server/app/router/api/index.ts b/src/core/server/app/router/api/index.ts
index 09b8bf3ab..b42da1e53 100644
--- a/src/core/server/app/router/api/index.ts
+++ b/src/core/server/app/router/api/index.ts
@@ -36,6 +36,10 @@ export function createAPIRouter(app: AppOptions, options: RouterOptions) {
   // Create a router.
   const router = express.Router();
 
+  router.use((req, res) => {
+    res.sendStatus(504);
+  });
+
   // Installation router.
   router.use("/install", createNewInstallRouter(app));
 

```

I'm still seeing the `Aborted in beforeRetry() callback` message, maybe a missed check?

You could also augment the `QueryRenderer` HOC to return the network error at that layer if it makes sense instead!

**Review by tessalt — APPROVED** [review]
nice

**Comment by kgardnr** [comment]
> nice

nice

**Comment by nick-funk** [comment]
> > nice
> 
> nice

nice

**Review by wyattjoh — APPROVED** [review]

**Pull request merged**
