### PR TITLE
Add initial Simplified Chinese translation

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?
Add initial Simplified Chinese translation.

## How do I test this PR?
- Make someone who could understand Simplified Chinese review it
- Define the build variable TALK_DEFAULT_LANG=zh_CN
- Build, start, and check

---
EDIT1:
- More details for testing.
- Now that I find somewhere in the files it writes "Translations are happening at https://translate.lingohub.com/the-coral-project/dashboard". Hmmm...

### CODE REVIEW

**Comment by kgardnr** [comment]
Thank you @MEL27, this is awesome! We are on holiday break right now, but will review and merge as soon as we're back in 2018. Thank you!

**Comment by ghost** [comment]
Happy Holidays! I made some corrections to locales/zh_CN.yml and added translations for plugins with the latest commit. The commit history is a mess now. Do collapse the commits if this pull request is to be merged.

**Comment by larrylizhao** [comment]
Hi, @MEL27. I'm a developer from Dowjones. It just happens that we also need a Chinese version of coral commenting module. I've worked on both simplified and traditional Chinese locales.
Now that there is already one for simplified Chinese, would you mind if I create another pr for traditional Chinese?

**Comment by ghost** [comment]
@larrylizhao I don't mind. It's kind of you to have asked me :)

**Comment by larrylizhao** [comment]
Thx!

**Review by kgardnr — DISMISSED** [review]

**Review by kgardnr — APPROVED** [review]

**Comment by kgardnr** [comment]
Thank you @MEL27, this is so exciting!! Thank you for this awesome contribution <3

**Pull request merged**
