### PR TITLE
Actions Metadata

### PR DESCRIPTION
**Pull request by wyattjoh**
## What does this PR do?

- Adds new Action structure
- Adds new Response structure
- Changes mutations to use new actions
- Added new docs endpoint http://localhost:3000/admin/docs

## How do I test this PR?

Test the following out in GraphiQL:

```graphql
fragment flagActionSummaryView on FlagActionSummary {
  reason
}

fragment actionSummaryView on ActionSummary {
  __typename
  count
  ...flagActionSummaryView
  current_user {
    id
    created_at
  }
}

fragment commentView on Comment {
  id
  body
  action_summaries {
    ...actionSummaryView
  }
  created_at
}

query LotsOfActions {
  assets {
    comments {
      ...commentView
      replies {
        ...commentView
      }
    }
  }
}

mutation CreateFlag($id: ID!) {
  createFlag(flag: {item_id: $id, item_type: COMMENTS, reason: "Offensive"}) {
    flag {
      id
    }
    errors {
      translation_key
    }
  }
}
```

Build static assets `yarn build` (or `yarn build-watch`) and view the docs page at http://localhost:3000/admin/docs.

### CODE REVIEW

**Comment by davidgljay** [comment]
Frontend is updated and ready for review, nice job @wyattjoh !

**Comment by davidgljay** [comment]
Note: I'm not worrying about optimizing the admin panel to display this data since that's all about to get refactored with GraphQL anyway.

**Comment by jde** [comment]
Tested this. The stream works perfectly.

This creates an issue in the moderation queue where the flagged comment doesn't get removed from the stream when an action is taken. QA approval granted as this issue will be naturally resolved by @okbel in her current work.

**Comment by riley** [comment]
I had a weird issue where if I liked something, reloaded, and clicked Like again it would unlike it, but if I re-liked it, the likes read `Liked 2`

**Comment by jde** [comment]
@riley I see the bug, but it is due to the way that the LikeButton component handles internal state and optimistic updates. I'll move this to an issue as it is out of the scope of this PR.

**Review by jde — APPROVED** [review]

**Pull request merged**
