### PR TITLE
New setting: Disable commenting site-wide

### PR DESCRIPTION
**Pull request by hellp**
## What does this PR do?

Implements feature #1540 

## How do I test this PR?

- Go to Configure > Stream Settings
- Enable the new setting *Deactivate commenting site-wide*; optionally provide a message
- Load the comment stream on any asset page
- Result:
  - existing comments are still there, but the input field has been replaced with the message that commenting is currently disabled
  - if you try to submit a comment from a (non-updated) UI input, the back-end will throw an `COMMENTING_DISABLED` error with a proper message

## TODO

- [x] Write a test case
- [x] Find a better name for the setting. Not happy with `globalSwitchoffEnable` for a switch that actually *disables* commenting. How about `commentingDisabled` or `commentingOff`?

### CODE REVIEW

**Comment by hellp** [comment]
If you have a good name for this setting, please tell me :)
Also if I should rebase or squash commits.

**Comment by wyattjoh** [comment]
Hey @hellp!

I'd recommend changing:

- `globalSwitchoffEnable` to `disableCommenting`
- `globalSwitchoffMessage` to `disableCommentingMessage`

And if you can, resolve the merge conflicts so I can give it a test!

**Comment by hellp** [comment]
- renamed
- rebased
- The Reply buttons on comments are now also hidden when commenting is disabled.

**Review by kgardnr — APPROVED** [review]

**Comment by kgardnr** [comment]
This looks good to be from a product perspective @hellp! I'll let @wyattjoh do a code review and then we should be good to merge.

Thanks again for contributing this!

**Pull request merged**
