### PR TITLE
Subscribe to comment updates

### PR DESCRIPTION
**Pull request by alinhle**
## What does this PR do?
- Comments and edits are merged into current state live using subscriptions.
- New comments are masked using a cursor based solution until user clicks on a button to show/load more comments.
- Replace former polling with subscriptions.
- Indicate new comments by showing a short yellow flash.
- Replies are live rendered without masking in a permlink view.
- All state updaters have been prepared to support deep threaded comments.

## Limitations
- If you have 2 windows logged in using the same user, you won't see the comments / replies of the same user coming from the other window.

### CODE REVIEW

**Comment by jde** [comment]
I'm seeing new comments incrementing the comment count by 2 instead of showing up in the stream.
comments-going-to-counts

(Chrome)

**Comment by jde** [comment]
Also,

Logged in.
Added a bunch of comments in another tab.
Clicked sign out.

Lots of comments were "pulled into" the counts:
screenshot 2017-06-05 16 02 28


(Chrome)

**Comment by alinhle** [comment]
Confirming the second reported issue. I need to wipe state when user logs out.

**Comment by alinhle** [comment]
Could be related to first issue.

**Comment by kgardnr** [comment]
I can't replicate the first issue you're seeing @jde fyi. I tested across 2 chrome windows, as well as across firefox and chrome.

Maybe it's because you have a ton of old test comments in your db?

**Comment by alinhle** [comment]
Working on another bug: Admin won't load.

**Review by kgardnr — APPROVED** [review]
LGTM! 💯

**Review by wyattjoh — DISMISSED** [review]
I need to add some changes to the server.

**Review by jde — APPROVED** [review]
LGTM

**Pull request merged**
